# Generated by Django 2.2 on 2020-08-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
